# Generated by Django 4.2.5 on 2023-09-08 15:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likecount', to=settings.AUTH_USER_MODEL),
        ),
    ]
